#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: {{ .Release.Name }}-payments-api
#spec:
#  replicas: {{ .Values.replicaCount }}
#  selector:
#    matchLabels:
#      app: payments-api
#  template:
#    metadata:
#      labels:
#        app: payments-api
#    spec:
#      containers:
#        - name: payments-api
#          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#          ports:
#            - containerPort: 5039
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "payments-api.fullname" . }}
  labels:
    app: {{ include "payments-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "payments-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "payments-api.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          stdin: true
