apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-end.fullname" . }}
  labels:
    app: {{ include "front-end.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "front-end.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "front-end.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            - mountPath: /app
              name: app-volume
      volumes:
        - name: app-volume
          hostPath:
            path: /api
            

